### ISSUE TITLE
Enhancement: separate the source code from the build artifacts

### ISSUE THREAD

**Issue by pspdada** [HITSZ-OpenAuto/hoa-moe#261]
Currently, the source code and build artifacts are together in this repository; the most obvious example is the 'blog' folder under 'content', which contains directly edited blog posts, while other folders, such as 'docs', are automatically generated by CI.

This can cause issues when forking and developing, as build artifacts might be included in pull requests, leading to unnecessary complications. I propose finding a method to separate the source code from the build artifacts, making contributions more convenient.

**Comment by kowyo** [comment]
> build artifacts might be included in pull requests

We can add identifier to tell whether workflow triggered by pull request or workflow dispatch (manual trigger & schedule), if it is triggered by pull request, we can just skip `EndBug/add-and-commit@v9` to avoid `build artifacts`.

For example:

```
- name: Commit and push changes
        if: trigger_event != pull_request_target
        uses: EndBug/add-and-commit@v9
        with:
          add: '["content", "scripts/filetrees/filetrees.json"]'
          pull: '--rebase --autostash'
          default_author: github_actions
          message: "ci: update course pages"
```

However, sometimes `build artifacts` are necessary to appear in pull request if you are changing their formatting and want to see effects before merging into main branch.
